-- Modern side owns the schema (shared standards, rule 1): every table, constraint and index is
-- declared here, not by hibernate.ddl-auto. Entities are checked against this with ddl-auto=validate.

CREATE TABLE policy (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_number      VARCHAR(40)  NOT NULL UNIQUE,
    holder_fiscal_code VARCHAR(32)  NOT NULL,
    start_date         DATE         NOT NULL,
    annual_premium     NUMERIC(12,2) NOT NULL
);

CREATE TABLE coverage (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code           VARCHAR(32)   NOT NULL,
    description    VARCHAR(255)  NOT NULL,
    insured_amount NUMERIC(14,2) NOT NULL,
    policy_id      BIGINT        NOT NULL REFERENCES policy(id) ON DELETE CASCADE
);

-- The index the legacy system was missing: holder_fiscal_code is the service's main filter.
-- The legacy module sequential-scans this; here it is an index scan. (docs/PERFORMANCE.md)
CREATE INDEX idx_policy_holder_fiscal_code ON policy (holder_fiscal_code);

-- Support the coverage fetch join / foreign key lookups.
CREATE INDEX idx_coverage_policy_id ON coverage (policy_id);
